export const type = {
  LOAD_COMMENTS: 'LOAD_COMMENTS',
  REMOVE_ALL_COMMENTS: 'REMOVE_ALL_COMMENTS',
  DELETE_REPLY: 'DELETE_REPLY',
  ADD_COMMENT: 'ADD_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  ADD_REPLY: 'ADD_REPLY',
  EDIT_REPLY: 'EDIT_REPLY',
};

export const controlType = {
  OPEN_FORM_EDIT_COMMENT: 'OPEN_FORM_EDIT_COMMENT',
  CLOSE_FORM_EDIT_COMMENT: 'CLOSE_FORM_EDIT_COMMENT',

  OPEN_FORM_ADD_REPLY: 'OPEN_FORM_ADD_REPLY',
  CLOSE_FORM_ADD_REPLY: 'CLOSE_FORM_ADD_REPLY',
  OPEN_FORM_EDIT_REPLY: 'OPEN_FORM_EDIT_REPLY',
  CLOSE_FORM_EDIT_REPLY: 'CLOSE_FORM_EDIT_REPLY',
};
